animal-count: false
log-animals: false
log-player-drops: false
buff-drops: 0
buff-shear-drops: 0
disable-snowgrow: false
disable-drops: false
disable-tnt: false
disable-invisibility-on-combat: false
lower-strength-potion-damage: false
health-potion-multiplier: 1.0
regen-potion-multiplier: 1.0
block-caps: true
block-villagers: false
safe-ice: false
safe-dispensers: false
safe-boats: true
safe-boats-delay: 6000
safe-boats-drop: true
safe-minecarts: true
safe-minecarts-delay: 6000
safe-minecarts-drop: true
safe-special-carts: true
remove-on-exit: false
safe-portals: false
pearl-damage: 0
leatherless-books: false
lock-horses: false
invulnerable-tame-horses: false
untame-pets: false
disabled-items:
    left-click: []
    right-click:
    - 261
    - 332
    - 344
    - 346
    - 381
    - 383
    dispensed:
    - 326
    - 327
allow-enchant-items: []
block-brew:
- 348
- 376
- 375
disable-buff:
- 329
restart-time: 7200
warn-restart-on-join: true
warn-restart-on-inventory-open: true
sprint-max-time: 40
