disable-snowgrow: false
disable-drops: false
log-animals: false
buff-drops: 0
block-caps: true
remove-on-exit: false
animal-count: false
safe-boats: true
safe-boats-delay: 6000
safe-boats-drop: true
safe-minecarts: true
safe-minecarts-delay: 6000
safe-minecarts-drop: true
safe-special-carts: true
disabled-items:
    left-click: []
    right-click:
    - 261
    - 332
    - 344
    - 346
    - 381
    - 383

