debug:
  disable-tnt: false

hook-logblock: false
log-entity-deaths:
  - DOLPHIN
  - TROPICAL_FISH
  - TURTLE
ignore-entity-deaths:
  - IRON_GOLEM

buff-drops: 0
buff-shear-drops: 0
disable-snowgrow: false
disable-drops: false
disable-tnt: false
disable-entity-block-damage: []
disable-golem-natural-spawn: false
enable-spigot-item-merging: true

block-caps: true
block-villagers: false
block-johnny: false
block-slime-moving-rails-and-carpets: true

safe-ice: false
safe-dispensers: false
safe-portals: false
allow-egg-hatching: true
disabled-items:
    left-click: []
    right-click:
    - 261
    - 332
    - 344
    - 346
    - 381
    - 383
    dispensed:
    - 326
    - 327

restart-times:
- "00-00"
- "02-00"
- "04-00"
- "06-00"
- "08-00"
- "10-00"
- "12-00"
- "14-00"
- "16-00"
- "18-00"
- "20-00"
- "22-00"

warn-restart-on-join: true
warn-restart-on-inventory-open: true
sprint-max-time: 40
countdown:
  maxTime: 15
  format: '>>$s<<'
  color: '&c'
  style: '&l'
  msgColor: '&a'
  msgStyle: '&l'
